/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_session__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_api_session__session_id__patch"];
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_api_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_source__source_id__get"];
        put?: never;
        post?: never;
        /** Delete Source */
        delete: operations["delete_source_api_source__source_id__delete"];
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source_api_source__source_id__patch"];
        trace?: never;
    };
    "/api/source/{source_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Media */
        get: operations["source_media_api_source__source_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source/{source_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Text */
        put: operations["edit_text_api_source__source_id__text_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/{session_id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Conversation */
        post: operations["add_conversation_api_session__session_id__conversation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe */
        post: operations["transcribe_api_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Weave */
        post: operations["run_weave_api_weave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weave/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Weave */
        get: operations["latest_weave_api_weave__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clarify
         * @description At most two short follow-up questions before weaving (docs/ART_DIRECTION.md §D).
         */
        post: operations["clarify_api_clarify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate-asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Asset */
        post: operations["generate_asset_api_generate_asset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/art/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Art File */
        get: operations["art_file_api_art__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demo Plan */
        get: operations["get_demo_plan_api_plans_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlphaMask */
        AlphaMask: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "alpha_mask";
            /** Asset Ref */
            asset_ref: string;
        };
        /** AnnotationOut */
        AnnotationOut: {
            /** Text */
            text: string;
            /** Source Ids */
            source_ids: string[];
            /** Target Source Id */
            target_source_id: string;
            /** Box */
            box: [
                number,
                number,
                number,
                number
            ];
        };
        /** ArtDirectionOut */
        ArtDirectionOut: {
            /** Requests */
            requests: components["schemas"]["ArtRequestOut"][];
            /** Annotations */
            annotations: components["schemas"]["AnnotationOut"][];
        };
        /** ArtRequestOut */
        ArtRequestOut: {
            /** Source Id */
            source_id: string;
            /** Moment Id */
            moment_id: string;
            /**
             * Tool
             * @enum {string}
             */
            tool: "tape_collage" | "doodle" | "scene_extension";
            /**
             * Treatment
             * @enum {string}
             */
            treatment: "DISTILL" | "EXTEND";
            /** Reason */
            reason: string;
            /**
             * Placement
             * @enum {string}
             */
            placement: "beside_original" | "replaces_print_zone";
        };
        /** AudioElement */
        AudioElement: {
            /** Id */
            id: string;
            bounds: components["schemas"]["Bounds"];
            /**
             * Rotation Deg
             * @default 0
             */
            rotation_deg: number;
            /** Z Index */
            z_index: number;
            /**
             * Provenance Interactive
             * @default true
             * @constant
             */
            provenance_interactive: true;
            /** Overlap Group Id */
            overlap_group_id?: string | null;
            /** Source Ids */
            source_ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "audio";
            /** Clip Start Ms */
            clip_start_ms: number;
            /** Clip End Ms */
            clip_end_ms: number;
            /** Transcript Excerpt */
            transcript_excerpt?: string | null;
        };
        /** Body_ingest_api_ingest_post */
        Body_ingest_api_ingest_post: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Files
             * @default []
             */
            files: string[];
            /** Text Json */
            text_json?: string | null;
        };
        /** Bounds */
        Bounds: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** BundleScore */
        BundleScore: {
            /** Total */
            total: number;
            /** Role Coverage */
            role_coverage: number;
            /** Salience */
            salience: number;
            /** Visual Diversity */
            visual_diversity: number;
            /** Emotional Coverage */
            emotional_coverage: number;
            /** Temporal Coverage */
            temporal_coverage: number;
            /** Grounding */
            grounding: number;
            /** Redundancy Penalty */
            redundancy_penalty: number;
        };
        /** Canvas */
        Canvas: {
            /**
             * Width
             * @default 1600
             * @constant
             */
            width: 1600;
            /**
             * Height
             * @default 1000
             * @constant
             */
            height: 1000;
            /**
             * Page Split X
             * @default 800
             * @constant
             */
            page_split_x: 800;
            /**
             * Outer Safe Margin
             * @default 48
             * @constant
             */
            outer_safe_margin: 48;
            gutter?: components["schemas"]["Gutter"];
        };
        /** CaptureSession */
        CaptureSession: {
            /**
             * Schema Version
             * @default 0.1.0
             * @constant
             */
            schema_version: "0.1.0";
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Allow Text Refinement
             * @default false
             */
            allow_text_refinement: boolean;
            /**
             * Weave Instruction
             * @description Author's optional free-text guidance for the weaver (e.g. 'focus on Shelly').
             */
            weave_instruction?: string | null;
            /**
             * Woven
             * @description True once a weave has finished for this session; Capture then starts a fresh notebook page.
             * @default false
             */
            woven: boolean;
            /**
             * Conversation
             * @default []
             */
            conversation: components["schemas"]["ConversationTurn"][];
            /** Fragments */
            fragments: components["schemas"]["SourceFragment"][];
        };
        /** ClarifyQuestion */
        ClarifyQuestion: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            /** Text */
            text: string;
            /**
             * Suggestions
             * @default []
             */
            suggestions: string[];
        };
        /**
         * ClarifyResult
         * @description The 'understand' step: what each photo shows, what each voice note says, and ≤N questions for what can't be seen.
         */
        ClarifyResult: {
            /** Questions */
            questions: components["schemas"]["ClarifyQuestion"][];
            /**
             * Photos
             * @default []
             */
            photos: components["schemas"]["PhotoSeen"][];
            /**
             * Voices
             * @default []
             */
            voices: components["schemas"]["VoiceHeard"][];
        };
        /** ConversationTurn */
        ConversationTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "weaver" | "author";
            /** Text */
            text: string;
            /** Source Id */
            source_id?: string | null;
            /** Question Id */
            question_id?: string | null;
            /** At */
            at?: string | null;
        };
        /** CreateSession */
        CreateSession: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id?: string;
        };
        /** DecorationElement */
        DecorationElement: {
            /** Id */
            id: string;
            bounds: components["schemas"]["Bounds"];
            /**
             * Rotation Deg
             * @default 0
             */
            rotation_deg: number;
            /** Z Index */
            z_index: number;
            /**
             * Provenance Interactive
             * @default false
             * @constant
             */
            provenance_interactive: false;
            /** Overlap Group Id */
            overlap_group_id?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "decoration";
            /**
             * Chrome Kind
             * @enum {string}
             */
            chrome_kind: "paper" | "gutter" | "page_shadow" | "generic_mount";
        };
        /** Detail */
        Detail: {
            /**
             * Label
             * @description What is visibly there, in plain words (e.g. "churros", "person").
             */
            label: string;
            /**
             * Box
             * @description Normalized [x0, y0, x1, y1] within the photo.
             */
            box: [
                number,
                number,
                number,
                number
            ];
        };
        /** DuplicateGroup */
        DuplicateGroup: {
            /** Id */
            id: string;
            /** Source Ids */
            source_ids: string[];
            /**
             * Kept Source Id
             * Format: uuid
             */
            kept_source_id: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "exact" | "perceptual" | "embedding";
        };
        /** EllipseMask */
        EllipseMask: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ellipse";
        };
        /** FragmentPreferences */
        FragmentPreferences: {
            /** Keep Original */
            keep_original: boolean;
            /** Source Instruction */
            source_instruction?: string | null;
        };
        /** GenerateAssetRequest */
        GenerateAssetRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
        };
        /** GeneratedAssetElement */
        GeneratedAssetElement: {
            /** Id */
            id: string;
            bounds: components["schemas"]["Bounds"];
            /**
             * Rotation Deg
             * @default 0
             */
            rotation_deg: number;
            /** Z Index */
            z_index: number;
            /**
             * Provenance Interactive
             * @default true
             * @constant
             */
            provenance_interactive: true;
            /** Overlap Group Id */
            overlap_group_id?: string | null;
            /** Source Ids */
            source_ids: string[];
            /** Mask */
            mask?: (components["schemas"]["RectangleMask"] | components["schemas"]["RoundedRectangleMask"] | components["schemas"]["EllipseMask"] | components["schemas"]["PolygonMask"] | components["schemas"]["SvgPathMask"] | components["schemas"]["AlphaMask"]) | null;
            /** Original Region Mask */
            original_region_mask?: (components["schemas"]["RectangleMask"] | components["schemas"]["RoundedRectangleMask"] | components["schemas"]["EllipseMask"] | components["schemas"]["PolygonMask"] | components["schemas"]["SvgPathMask"] | components["schemas"]["AlphaMask"]) | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "generated_asset";
            /**
             * Treatment
             * @enum {string}
             */
            treatment: "ANNOTATE" | "EXTEND" | "DISTILL";
            /**
             * Art Style
             * @enum {string}
             */
            art_style: "tape_collage" | "gathered_scenes" | "doodle";
            /** Asset Request Id */
            asset_request_id: string;
            /** Asset Ref */
            asset_ref: string;
            /**
             * Generation Mode
             * @enum {string}
             */
            generation_mode: "live" | "cache" | "fallback";
        };
        /** Gutter */
        Gutter: {
            /**
             * X
             * @default 776
             * @constant
             */
            x: 776;
            /**
             * Width
             * @default 48
             * @constant
             */
            width: 48;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaskPoint */
        MaskPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** MemoryAtom */
        MemoryAtom: {
            /** Id */
            id: string;
            /** Source Ids */
            source_ids: string[];
            /** Event */
            event: string;
            /**
             * People
             * @default []
             */
            people: string[];
            /** Place */
            place?: string | null;
            /**
             * Objects
             * @default []
             */
            objects: string[];
            /**
             * Moods
             * @default []
             */
            moods: string[];
            /**
             * Themes
             * @default []
             */
            themes: string[];
            /** Captured At */
            captured_at?: string | null;
            /** Salience */
            salience: number;
            /** Verbatim Text */
            verbatim_text?: string | null;
            /**
             * Must Preserve
             * @default true
             */
            must_preserve: boolean;
            /** Subject Kind */
            subject_kind?: ("object" | "scene") | null;
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["Detail"][];
        };
        /** Moment */
        Moment: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Atom Ids */
            atom_ids: string[];
            /** Source Ids */
            source_ids: string[];
            /**
             * Image Source Ids
             * @default []
             */
            image_source_ids: string[];
            /** Summary */
            summary: string;
            /**
             * People
             * @default []
             */
            people: string[];
            /** Place */
            place?: string | null;
            /**
             * Moods
             * @default []
             */
            moods: string[];
            /** Salience */
            salience: number;
            /** Time Range */
            time_range?: [
                string,
                string
            ] | null;
        };
        /** PhotoElement */
        PhotoElement: {
            /** Id */
            id: string;
            bounds: components["schemas"]["Bounds"];
            /**
             * Rotation Deg
             * @default 0
             */
            rotation_deg: number;
            /** Z Index */
            z_index: number;
            /**
             * Provenance Interactive
             * @default true
             * @constant
             */
            provenance_interactive: true;
            /** Overlap Group Id */
            overlap_group_id?: string | null;
            /** Source Ids */
            source_ids: string[];
            /** Mask */
            mask?: (components["schemas"]["RectangleMask"] | components["schemas"]["RoundedRectangleMask"] | components["schemas"]["EllipseMask"] | components["schemas"]["PolygonMask"] | components["schemas"]["SvgPathMask"] | components["schemas"]["AlphaMask"]) | null;
            /** Original Region Mask */
            original_region_mask?: (components["schemas"]["RectangleMask"] | components["schemas"]["RoundedRectangleMask"] | components["schemas"]["EllipseMask"] | components["schemas"]["PolygonMask"] | components["schemas"]["SvgPathMask"] | components["schemas"]["AlphaMask"]) | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "photo";
            /** Source Asset Id */
            source_asset_id: string;
            /**
             * Treatment
             * @enum {string}
             */
            treatment: "PRESERVE" | "ANNOTATE" | "EXTEND";
            /**
             * Fit
             * @enum {string}
             */
            fit: "cover" | "contain";
        };
        /** PhotoSeen */
        PhotoSeen: {
            /** Source Id */
            source_id: string;
            /** Captured At */
            captured_at?: string | null;
            /** Subject Kind */
            subject_kind?: ("object" | "scene") | null;
            /**
             * Labels
             * @default []
             */
            labels: string[];
            /**
             * People
             * @default []
             */
            people: string[];
        };
        /** PolygonMask */
        PolygonMask: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "polygon";
            /** Points */
            points: components["schemas"]["MaskPoint"][];
        };
        /** ProviderInfo */
        ProviderInfo: {
            /**
             * Reasoning
             * @enum {string}
             */
            reasoning: "live" | "fixture" | "heuristic";
            /** Reasoning Model */
            reasoning_model?: string | null;
            /**
             * Embeddings
             * @enum {string}
             */
            embeddings: "siglip2" | "fallback";
            /** Embedding Model */
            embedding_model?: string | null;
            /**
             * Cross Modal
             * @description True when text queries and images share one embedding space (SigLIP 2).
             */
            cross_modal: boolean;
        };
        /** RectangleMask */
        RectangleMask: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rectangle";
        };
        /** ResolvedVisualPlan */
        ResolvedVisualPlan: {
            /** Schema Version */
            schema_version: string;
            /** Plan Id */
            plan_id: string;
            /** Plan Revision */
            plan_revision: number;
            /** Session Id */
            session_id: string;
            canvas: components["schemas"]["Canvas"];
            /** Title */
            title: string;
            /** Palette */
            palette: string[];
            /** Uses Timeline */
            uses_timeline: boolean;
            /**
             * Status
             * @constant
             */
            status: "resolved";
            /** Elements */
            elements: (components["schemas"]["PhotoElement"] | components["schemas"]["TextElement"] | components["schemas"]["AudioElement"] | components["schemas"]["GeneratedAssetElement"] | components["schemas"]["DecorationElement"])[];
        };
        /** RoleCandidates */
        RoleCandidates: {
            /** Role */
            role: string;
            /** Intent */
            intent: string;
            /** Query */
            query: string;
            /** Candidate Moment Ids */
            candidate_moment_ids: string[];
            /** Scores */
            scores: number[];
        };
        /** RoleIntent */
        RoleIntent: {
            /** Role */
            role: string;
            /** Intent */
            intent: string;
            /**
             * Query
             * @description Short visual description used for embedding retrieval.
             */
            query: string;
        };
        /** RoundedRectangleMask */
        RoundedRectangleMask: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rounded_rectangle";
            /** Radius Px */
            radius_px: number;
        };
        /** ScoredBundle */
        ScoredBundle: {
            /**
             * Seed
             * @enum {string}
             */
            seed: "anchor" | "alternative" | "baseline";
            /** Moment Ids */
            moment_ids: string[];
            /**
             * Roles
             * @description moment_id → narrative role
             */
            roles: {
                [key: string]: string;
            };
            score: components["schemas"]["BundleScore"];
            /**
             * Expansion Log
             * @default []
             */
            expansion_log: string[];
        };
        /** SessionPreferences */
        SessionPreferences: {
            /** Allow Text Refinement */
            allow_text_refinement?: boolean | null;
            /** Weave Instruction */
            weave_instruction?: string | null;
        };
        /** SourceFragment */
        SourceFragment: {
            /**
             * Schema Version
             * @default 0.1.0
             * @constant
             */
            schema_version: "0.1.0";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Modality
             * @enum {string}
             */
            modality: "image" | "text" | "audio";
            /** Original Media Ref */
            original_media_ref?: string | null;
            /** Original Text */
            original_text?: string | null;
            /** Filename */
            filename?: string | null;
            /** Media Type */
            media_type?: string | null;
            /**
             * Byte Size
             * @default 0
             */
            byte_size: number;
            /** Captured At */
            captured_at?: string | null;
            /**
             * Keep Original
             * @default true
             */
            keep_original: boolean;
            /** Source Instruction */
            source_instruction?: string | null;
            transcript?: components["schemas"]["SourceTranscript"] | null;
        };
        /** SourceTranscript */
        SourceTranscript: {
            /** Duration Ms */
            duration_ms: number;
            /** Segments */
            segments: components["schemas"]["TranscriptSegment"][];
            /**
             * Schema Version
             * @default 0.1.0
             * @constant
             */
            schema_version: "0.1.0";
            /** Source Ids */
            source_ids: string[];
        };
        /** StageTiming */
        StageTiming: {
            /** Stage */
            stage: string;
            /** Ms */
            ms: number;
        };
        /** StickerPickOut */
        StickerPickOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Src */
            src: string;
            /** Kind */
            kind: string;
            /** Chosen */
            chosen: boolean;
            /** Score */
            score: number;
            /** Matched */
            matched: string[];
            /** Color Fit */
            color_fit: number;
            /** Reason */
            reason: string;
        };
        /** StoryIntent */
        StoryIntent: {
            /** Intent */
            intent: string;
            /** Title */
            title: string;
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /**
             * Roles
             * @description First role is always the Anchor.
             */
            roles: components["schemas"]["RoleIntent"][];
        };
        /** SvgPathMask */
        SvgPathMask: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "svg_path";
            /** Path */
            path: string;
        };
        /** TextEdit */
        TextEdit: {
            /** Text */
            text: string;
        };
        /** TextElement */
        TextElement: {
            /** Id */
            id: string;
            bounds: components["schemas"]["Bounds"];
            /**
             * Rotation Deg
             * @default 0
             */
            rotation_deg: number;
            /** Z Index */
            z_index: number;
            /**
             * Provenance Interactive
             * @default true
             * @constant
             */
            provenance_interactive: true;
            /** Overlap Group Id */
            overlap_group_id?: string | null;
            /** Source Ids */
            source_ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Text */
            text: string;
            /**
             * Text Mode
             * @enum {string}
             */
            text_mode: "verbatim" | "refined";
            /**
             * Style Role
             * @enum {string}
             */
            style_role: "title" | "body" | "quote" | "caption";
            /** Font Size Px */
            font_size_px: number;
            /**
             * Align
             * @enum {string}
             */
            align: "left" | "center" | "right";
        };
        /** TranscribeRequest */
        TranscribeRequest: {
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
        };
        /** TranscriptSegment */
        TranscriptSegment: {
            /** Text */
            text: string;
            /** Clip Start Ms */
            clip_start_ms: number;
            /** Clip End Ms */
            clip_end_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifierReport */
        VerifierReport: {
            /** Coverage */
            coverage: number;
            /** Coherence */
            coherence: number;
            /** Complementarity */
            complementarity: number;
            /** Groundedness */
            groundedness: number;
            /** Visual Diversity */
            visual_diversity: number;
            /** Weakest Moment Id */
            weakest_moment_id?: string | null;
            /** Replacement Moment Id */
            replacement_moment_id?: string | null;
            /** Rationale */
            rationale: string;
        };
        /** VoiceHeard */
        VoiceHeard: {
            /** Source Id */
            source_id: string;
            /**
             * Shown As Text
             * @description True for "Turn into words"; False = understood quietly, stays as your voice on the page.
             */
            shown_as_text: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "transcribed" | "unavailable" | "failed";
            /** Text */
            text?: string | null;
            /** Detail */
            detail?: string | null;
        };
        /** WeaveRequest */
        WeaveRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** WeaveResult */
        WeaveResult: {
            /**
             * Schema Version
             * @default 0.1.0
             * @constant
             */
            schema_version: "0.1.0";
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            providers: components["schemas"]["ProviderInfo"];
            /** Atoms */
            atoms: components["schemas"]["MemoryAtom"][];
            /** Duplicate Groups */
            duplicate_groups: components["schemas"]["DuplicateGroup"][];
            /** Moments */
            moments: components["schemas"]["Moment"][];
            story: components["schemas"]["StoryIntent"];
            /** Role Candidates */
            role_candidates: components["schemas"]["RoleCandidates"][];
            /** Seeds */
            seeds: components["schemas"]["ScoredBundle"][];
            selected: components["schemas"]["ScoredBundle"];
            verifier: components["schemas"]["VerifierReport"];
            /**
             * Verifier Mode
             * @enum {string}
             */
            verifier_mode: "live" | "fixture" | "heuristic";
            /**
             * Replacement
             * @description "old → new" when the one allowed replacement was applied.
             */
            replacement?: string | null;
            baseline: components["schemas"]["ScoredBundle"];
            /** Palette */
            palette: string[];
            /** Uses Timeline */
            uses_timeline: boolean;
            art?: components["schemas"]["ArtDirectionOut"] | null;
            /**
             * Stickers
             * @default []
             */
            stickers: components["schemas"]["StickerPickOut"][];
            /**
             * Day
             * @description The day most photos were taken on; the memory is filed under it.
             */
            day?: string | null;
            /** Timings */
            timings: components["schemas"]["StageTiming"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_session__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionPreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_api_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_api_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_api_source__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFragment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_source__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_source__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FragmentPreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFragment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_media_api_source__source_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_text_api_source__source_id__text_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFragment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_conversation_api_session__session_id__conversation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationTurn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_api_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceTranscript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_weave_api_weave_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_weave_api_weave__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clarify_api_clarify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_asset_api_generate_asset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateAssetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    art_file_api_art__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_demo_plan_api_plans_demo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedVisualPlan"];
                };
            };
        };
    };
}
